export const moveslist = [
    {
      id: 1,
      name: "Absorb",
      type: "grass",
      power: 20,
      accuracy: 100,
      pp: 20,
      description: "User recovers half the HP inflicted on opponent.",
      status: "",
      statchange: "healthfromdamage2",
      multi: "no",
      
    },
    {
        id: 2,
        name: "Acid",
        type: "poison",
        power: 40,
        accuracy: 100,
        pp: 30,
        description: "May lower opponent's Special Defense.",
        status: "",
        statchange: "defensedown1-33",
        multi: "no",
        
    },
    {
        id: 3,
        name: "Acid Armor",
        type: "poison",
        power: 0,
        accuracy: "",
        pp: 20,
        description: "Sharply raises user's Defense.",
        status: "",
        statchange: "defenseup2",
        multi: "no",
        
    },
    {
        id: 4,
        name: "Agility",
        type: "psychic",
        power: 0,
        accuracy: "",
        pp: 30,
        description: "Sharply raises user's Speed.",
        status: "",
        statchange: "speedup2",
        multi: "no",
        
    },
    {
        id: 5,
        name: "Amnesia",
        type: "psychic",
        power: 0,
        accuracy: "",
        pp: 20,
        description: "Sharply raises user's Special.",
        status: "",
        statchange: "specialup2",
        multi: "no",
        
    },
    {
        id: 6,
        name: "Aurora Beam",
        type: "ice",
        power: 65,
        accuracy: 100,
        pp: 20,
        description: "May lower opponent's Attack.",
        status: "",
        statchange: "attackdown1-10",
        multi: "no",
        
    },
    {
        id: 7,
        name: "Barrage",
        type: "normal",
        power: 15,
        accuracy: 85,
        pp: 20,
        description: "Hits 2-5 times in one turn.",
        status: "",
        statchange: "",
        multi: "2-5hits",
        
    },
    {
        id: 8,
        name: "Barrier",
        type: "psychic",
        power: 0,
        accuracy: "",
        pp: 20,
        description: "Sharply raises user's Defense.",
        status: "",
        statchange: "defenceup2",
        multi: "no",
        
    },
    {
        id: 9,
        name: "Bide",
        type: "normal",
        power: 0,
        accuracy: "",
        pp: 10,
        description: "User takes damage for two turns then strikes back double.",
        status: "",
        statchange: "",
        multi: "delay2",
        
    },
    {
        id: 10,
        name: "Bind",
        type: "normal",
        power: 15,
        accuracy: 85,
        pp: 20,
        description: "Traps opponent, damaging them for 4-5 turns.",
        status: "",
        statchange: "",
        multi: "2-5turns",
        
    },
    {
        id: 11,
        name: "Bite",
        type: "normal",
        power: 60,
        accuracy: 100,
        pp: 25,
        description: "May cause flinching.",
        status: "flinch-30",
        statchange: "",
        multi: "no",
        
    },
    {
        id: 12,
        name: "Blizzard",
        type: "ice",
        power: 120,
        accuracy: 90,
        pp: 5,
        description: "May cause flinching.",
        status: "flinch-30",
        statchange: "",
        multi: "no",
        
    },

]