export const pokedex = [
    {
      id: 1,
      name: "Bulbasaur",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/bulbasaur.png",
      brockurl: "https://youtu.be/GL5oUnAR7lI?t=561",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Win",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 2,
      name: "Ivysaur",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/ivysaur.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 3,
      name: "Venusaur",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/venusaur.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 4,
      name: "Charmander",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/charmander.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 5,
      name: "Charmeleon",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/charmeleon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 6,
      name: "Charizard",
      type1: "fire",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/charizard.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 7,
      name: "Squirtle",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/squirtle.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 8,
      name: "Wartortle",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/wartortle.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 9,
      name: "Blastoise",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/blastoise.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 10,
      name: "Caterpie",
      type1: "bug",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/caterpie.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 11,
      name: "Metapod",
      type1: "bug",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/metapod.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 12,
      name: "Butterfree",
      type1: "bug",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/butterfree.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 13,
      name: "Weedle",
      type1: "bug",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/weedle.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    
    {
      id: 14,
      name: "Kakuna",
      type1: "bug",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kakuna.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    
    {
      id: 15,
      name: "Beedrill",
      type1: "bug",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/beedrill.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 16,
      name: "Pidgey",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/pidgey.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 17,
      name: "Pidgeotto",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/pidgeotto.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 18,
      name: "Pidgeot",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/pidgeot.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 19,
      name: "Rattata",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/rattata.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 20,
      name: "Raticate",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/raticate.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 21,
      name: "Spearow",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/spearow.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 22,
      name: "Fearow",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/fearow.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 23,
      name: "Ekans",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/ekans.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 24,
      name: "Arbok",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/arbok.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 25,
      name: "Pikachu",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/pikachu.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 26,
      name: "Raichu",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/raichu.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 27,
      name: "Sandshrew",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/sandshrew.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 28,
      name: "Sandslash",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/sandslash.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 29,
      name: "Nidoran-F",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidoranf.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 30,
      name: "Nidorina",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidorina.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 31,
      name: "Nidoqueen",
      type1: "poison",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidoqueen.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 32,
      name: "Nidoran-M",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidoranm.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 33,
      name: "Nidorino",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidorino.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 34,
      name: "Nidoking",
      type1: "poison",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/nidoking.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 35,
      name: "Clefairy",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/clefairy.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 36,
      name: "Clefable",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/clefable.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 37,
      name: "Vulpix",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/vulpix.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 38,
      name: "Ninetales",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/ninetales.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 39,
      name: "Jigglypuff",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/jigglypuff.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 40,
      name: "Wigglytuff",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/wigglytuff.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 41,
      name: "Zubat",
      type1: "poison",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/zubat.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 42,
      name: "Golbat",
      type1: "poison",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/golbat.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 43,
      name: "Oddish",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/oddish.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 44,
      name: "Gloom",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/gloom.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 45,
      name: "Vileplume",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/vileplume.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 46,
      name: "Paras",
      type1: "bug",
      type2: "grass",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/paras.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 47,
      name: "Parasect",
      type1: "bug",
      type2: "grass",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/parasect.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 48,
      name: "Venonat",
      type1: "bug",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/venonat.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 49,
      name: "Venomoth",
      type1: "bug",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/venomoth.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 50,
      name: "Diglett",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/diglett.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 51,
      name: "Dugtrio",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dugtrio.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "https://youtu.be/doquMrvzMSg",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Win",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 52,
      name: "Meowth",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/meowth.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 53,
      name: "Persian",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/persian.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 54,
      name: "Psyduck",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/psyduck.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 55,
      name: "Golduck",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/golduck.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 56,
      name: "Mankey",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/mankey.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 57,
      name: "Primeape",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/primeape.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 58,
      name: "Growlithe",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/growlithe.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 59,
      name: "Arcanine",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/arcanine.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 60,
      name: "Poliwag",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/poliwag.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 61,
      name: "Poliwhirl",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/poliwhirl.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 62,
      name: "Poliwrath",
      type1: "water",
      type2: "fighting",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/poliwrath.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 63,
      name: "Abra",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/abra.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 64,
      name: "Kadabra",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kadabra.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 65,
      name: "Alakazam",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/alakazam.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 66,
      name: "Machop",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/machop.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 67,
      name: "Machoke",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/machoke.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 68,
      name: "Machamp",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/machamp.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 69,
      name: "Bellsprout",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/bellsprout.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 70,
      name: "Weepinbell",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/weepinbell.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 71,
      name: "Victreebel",
      type1: "grass",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/victreebel.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 72,
      name: "Tentacool",
      type1: "water",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/tentacool.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 73,
      name: "Tentacruel",
      type1: "water",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/tentacruel.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 74,
      name: "Geodude",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/geodude.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 75,
      name: "Graveler",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/graveler.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 76,
      name: "Golem",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/golem.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 77,
      name: "Ponyta",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/ponyta.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 78,
      name: "Rapidash",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/rapidash.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 79,
      name: "Slowpoke",
      type1: "water",
      type2: "psychic",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/slowpoke.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 80,
      name: "Slowbro",
      type1: "water",
      type2: "psychic",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/slowbro.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 81,
      name: "Magnemite",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/magnemite.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 82,
      name: "Magneton",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/magneton.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 83,
      name: "Farfetchd",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/farfetchd.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 84,
      name: "Doduo",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/doduo.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 85,
      name: "Dodrio",
      type1: "flying",
      type2: "normal",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dodrio.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 86,
      name: "Seel",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/seel.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 87,
      name: "Dewgong",
      type1: "water",
      type2: "ice",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dewgong.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 88,
      name: "Grimer",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/grimer.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 89,
      name: "Muk",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/muk.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 90,
      name: "Shellder",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/shellder.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 91,
      name: "Cloyster",
      type1: "water",
      type2: "ice",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/cloyster.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "https://youtu.be/vXVQpgaOpmQ",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Win",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 92,
      name: "Gastly",
      type1: "ghost",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/gastly.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 93,
      name: "Haunter",
      type1: "ghost",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/haunter.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 94,
      name: "Gengar",
      type1: "ghost",
      type2: "poison",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/gengar.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 95,
      name: "Onix",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/onix.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 96,
      name: "Drowzee",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/drowzee.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 97,
      name: "Hypno",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/hypno.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 98,
      name: "Krabby",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/krabby.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 99,
      name: "Kingler",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kingler.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 100,
      name: "Voltorb",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/voltorb.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 101,
      name: "Electrode",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/electrode.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 102,
      name: "Exeggcute",
      type1: "grass",
      type2: "psychic",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/exeggcute.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 103,
      name: "Exeggutor",
      type1: "grass",
      type2: "psychic",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/exeggutor.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 104,
      name: "Cubone",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/cubone.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 105,
      name: "Marowak",
      type1: "ground",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/marowak.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 106,
      name: "Hitmonlee",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/hitmonlee.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 107,
      name: "Hitmonchan",
      type1: "fighting",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/hitmonchan.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 108,
      name: "Lickitung",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/lickitung.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 109,
      name: "Koffing",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/koffing.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 110,
      name: "Weezing",
      type1: "poison",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/weezing.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 111,
      name: "Rhyhorn",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/rhyhorn.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 112,
      name: "Rhydon",
      type1: "rock",
      type2: "ground",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/rhydon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 113,
      name: "Chansey",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/chansey.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 114,
      name: "Tangela",
      type1: "grass",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/tangela.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 115,
      name: "Kangaskhan",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kangaskhan.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 116,
      name: "Horsea",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/horsea.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 117,
      name: "Seadra",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/seadra.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 118,
      name: "Goldeen",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/goldeen.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 119,
      name: "Seaking",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/seaking.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 120,
      name: "Staryu",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/staryu.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 121,
      name: "Starmie",
      type1: "water",
      type2: "psychic",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/starmie.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 122,
      name: "Mr-Mime",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/mrmime.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 123,
      name: "Scyther",
      type1: "bug",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/scyther.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 124,
      name: "Jynx",
      type1: "psychic",
      type2: "ice",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/jynx.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 125,
      name: "Electabuzz",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/electabuzz.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 126,
      name: "Magmar",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/magmar.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 127,
      name: "Pinsir",
      type1: "bug",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/pinsir.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 128,
      name: "Tauros",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/tauros.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 129,
      name: "Magikarp",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/magikarp.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 130,
      name: "Gyarados",
      type1: "water",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/gyarados.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 131,
      name: "Lapras",
      type1: "water",
      type2: "ice",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/lapras.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 132,
      name: "Ditto",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/ditto.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 133,
      name: "Eevee",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/eevee.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 134,
      name: "Vaporeon",
      type1: "water",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/vaporeon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 135,
      name: "Jolteon",
      type1: "electric",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/jolteon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 136,
      name: "Flareon",
      type1: "fire",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/flareon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 137,
      name: "Porygon",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/porygon.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 138,
      name: "Omanyte",
      type1: "water",
      type2: "rock",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/omanyte.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 139,
      name: "Omastar",
      type1: "water",
      type2: "rock",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/omastar.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 140,
      name: "Kabuto",
      type1: "water",
      type2: "rock",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kabuto.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 141,
      name: "Kabutops",
      type1: "water",
      type2: "rock",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/kabutops.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Win",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 142,
      name: "Aerodactyl",
      type1: "rock",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/aerodactyl.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 143,
      name: "Snorlax",
      type1: "normal",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/snorlax.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 144,
      name: "Articuno",
      type1: "flying",
      type2: "ice",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/articuno.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 145,
      name: "Zapdos",
      type1: "flying",
      type2: "electric",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/zapdos.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 146,
      name: "Moltres",
      type1: "flying",
      type2: "fire",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/moltres.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 147,
      name: "Dratini",
      type1: "dragon",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dratini.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 148,
      name: "Dragonair",
      type1: "dragon",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dragonair.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 149,
      name: "Dragonite",
      type1: "dragon",
      type2: "flying",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/dragonite.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 150,
      name: "Mewtwo",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/mewtwo.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Win",
      vsmisty: "Win",
      vsrival: "Upcoming",
      vselite: "Upcoming",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
    {
      id: 151,
      name: "Mew",
      type1: "psychic",
      type2: "",
      description: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
      image: "/pokemon/mew.png",
      brockurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      mistyurl: "https://youtu.be/NoaZuHIO-DQ?t=468",
      rivalurl: "",
      eliteurl: "",
      vsbrock: "Loss",
      vsmisty: "-",
      vsrival: "-",
      vselite: "-",
      hp: 45,
      attack: 49,
      defense: 49,
      special: 65,
      speed: 45
    },
  ];